### ISSUE TITLE
Passing Error to payloadCreator

### ISSUE THREAD

**Issue by mxl** [redux-utilities/redux-actions#255] opened 2017-11-27 12:47 UTC
Currently it's not possible to pass `Error` object to `payloadCreator` because it's intercepted by [this line](https://github.com/reduxactions/redux-actions/blob/master/src/createAction.js#L14).

**Comment by mslipper** [comment] 2018-01-16 05:05
I'll have to look into this. Should be able to give you a more complete response this weekend.

**Comment by Rmannn** [comment] 2018-01-31 17:56
Any news on this ?

**Comment by sanbornhilland** [comment] 2018-04-03 18:28
I think this is a duplicate of this ticket that was closed, working as designed #194 but I'm going to move my comment here instead because this ticket is still open.

> Just ended up here because of some really confusing debugging as well. I agree this is unexpected behaviour and could be more clearly documented. Is there a way to opt out of this behaviour? If not, would you be willing consider adding an option for that?

**Comment by hamaron** [comment] 2018-06-08 23:49
I'm also the one who spent hours on this problem, and I found the very interesting discussion in #65 that decided not to call payload creator if the passed object is an instance of Error.

IMHO, it doesn't makes much sense to me to bypass payload creator for Error instances because an action creator should not have business logic inside it. I'd argue that we should create another action if you want to dispatch actions whose payload's types are different each other. This way, we don't have the inconsistent behavior no matter what kind of object we pass to the method (Which I believe is the presumption everyone shares)

Having said that, I know that the API has been exposed for years as it is, so how about having an option not to bypass the payload creator even if the payload type is of Error?
I'd actually be willing to opting out the confusing bypassing behavior for new users to come, but I can be more conservative/defensive.
If this sounds good, I'd be happy to send a PR for this issue.

**Comment by sanbornhilland** [comment] 2018-06-11 16:34
@hamaron a while ago I started writing a patch for this but ran into some trouble because the `catch` behaviour is dependent on the way errors are uniquely handled. It wasn't obvious to me how to maintain the current API in a non-kludgy way without breaking this feature. I think making this opt-in as you suggest would be the least disruptive approach. So I could get behind it. Still, not breaking other feature in the process seems important even for those who opt-in.

**Comment by alexander-heimbuch** [comment] 2023-03-05 19:06
This issue is a while open and I will close it as it seem blocking. Feel free to comment and I will reopen it  if you feel that this is still relevant.

**Closed by alexander-heimbuch** 2023-03-05 19:06 UTC
Labels: bug
